// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AlphaDrive.Mac.Diagnostics.Models;

namespace AlphaDrive.Mac.Diagnostics
{
    public partial class DiagnosisViewController : NSViewController
    {
        public static DiagnosisViewController CreateController()
        {
            var board = NSStoryboard.FromName("DiagnosisStoryboard", null);
            return (DiagnosisViewController)board.InstantiateControllerWithIdentifier("DiagnosisViewController");
        }

        public DiagnosisViewController(IntPtr handle) : base(handle)
        {
        }

        private DiagnosisInfoModel _diagnosisInfo = new DiagnosisInfoModel();

        [Export("DiagnosisInfoModel")]
        public DiagnosisInfoModel DiagnosisInfoModel
        {
            get { return _diagnosisInfo; }
            set
            {
                WillChangeValue(nameof(DiagnosisInfoModel));
                _diagnosisInfo = value;
                DidChangeValue(nameof(DiagnosisInfoModel));
            }
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            DiagnosisInfoModel = new DiagnosisInfoModel();
            DiagnosisInfoModel.LoadSettings();
        }

    }
}
