// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AlphaDrive.Mac
{
	public partial class DiagnosisViewController : NSViewController
	{
		public DiagnosisViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
