// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AlphaDrive.Mac.ListItems;
using System.Linq;

namespace AlphaDrive.Mac
{
	public partial class SettingsViewController : NSViewController
	{
        #region Computed Properties
        public override NSObject RepresentedObject
        {
            get
            {
                return base.RepresentedObject;
            }
            set
            {
                base.RepresentedObject = value;
                // Update the view, if already loaded.
            }
        }
        #endregion


		public SettingsViewController (IntPtr handle) : base (handle)
		{

		}

        private AlphaDrive.Mac.FileSettings.FileSettingsViewController _fileSettingsViewControl;

        private AlphaDrive.Mac.Diagnostics.DiagnosisViewController _diagnosisViewControl;


        private void OnItemClicked(object sender)
        {
            if (sender is SourceListItem item)
            {
                MainPane.Subviews.FirstOrDefault()?.RemoveFromSuperview();
                if (item.Tag == "0")
                {
                    MainPane.AddSubview(_fileSettingsViewControl.View);
                }
                else if (item.Tag == "8")
                {
                    MainPane.AddSubview(_diagnosisViewControl.View);
                }
                
            }

        }


        public override void AwakeFromNib()
        {
            base.AwakeFromNib();


            SourceList.Initialize();

            var mainSection = new SourceListItem("Main");

            mainSection.AddItem(new SourceListItem("File Settings", null, "0", OnItemClicked));
            mainSection.AddItem(new SourceListItem("Outlook integration", null, "1", OnItemClicked));
            mainSection.AddItem(new SourceListItem("Browser link", null, "2", OnItemClicked));;
            mainSection.AddItem(new SourceListItem("HotDocs integration", null, "3", OnItemClicked));
            mainSection.AddItem(new SourceListItem("Optical Character Recogntion", null, "4", OnItemClicked));
            mainSection.AddItem(new SourceListItem("Microsoft Office", null, "5", OnItemClicked));
            SourceList.AddItem(mainSection);

            var advanceSection = new SourceListItem("Advanced");
            advanceSection.AddItem(new SourceListItem("Click to call", null, "6", OnItemClicked));
            advanceSection.AddItem(new SourceListItem("Data Export", null, "7", OnItemClicked));
            advanceSection.AddItem(new SourceListItem("Diagnosis", null, "8", OnItemClicked));
            SourceList.AddItem(advanceSection);

            // Display side list
            SourceList.ReloadData();

            SourceList.ExpandItem(null, true);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            //_fileSettingsViewControl = (FileSettingsViewController)this.Storyboard.InstantiateControllerWithIdentifier("FileSettingsViewController");

            _fileSettingsViewControl = AlphaDrive.Mac.FileSettings.FileSettingsViewController.CreateController();
            _diagnosisViewControl = AlphaDrive.Mac.Diagnostics.DiagnosisViewController.CreateController();
            //NSStoryboard.FromName("DiagnosisStoryboard")

            //_diagnosisViewControl = (AlphaDrive.Mac.Diagnostics.DiagnosisViewController)this.Storyboard.InstantiateControllerWithIdentifier("DiagnosisViewController");

            MainPane.AddSubview(_fileSettingsViewControl.View);

        }

	}
}
